seed: 42
models:
  separate: false
  policy:
    class: GaussianMixin
    clip_actions: false
    clip_log_std: true
    min_log_std: -20.0
    max_log_std: 2.0
    initial_log_std: 0.0
    network:
    - name: features_extractor
      input: permute(STATES["vision_obs"], (0, 3, 1, 2))
      layers:
      - conv2d:
          out_channels: 16
          kernel_size: 4
          stride: 2
          padding: 0
      - conv2d:
          out_channels: 4
          kernel_size: 3
          stride: 1
          padding: 0
      - flatten
      activations: relu
    - name: net
      input: concatenate([features_extractor, STATES["proprio_obs"]])
      layers:
      - 256
      - 128
      - 64
      activations: elu
    output: ACTIONS
  value:
    class: DeterministicMixin
    clip_actions: false
    network:
    - name: features_extractor
      input: permute(STATES["vision_obs"], (0, 3, 1, 2))
      layers:
      - conv2d:
          out_channels: 16
          kernel_size: 4
          stride: 2
          padding: 0
      - conv2d:
          out_channels: 4
          kernel_size: 3
          stride: 1
          padding: 0
      - flatten
      activations: relu
    - name: net
      input: concatenate([features_extractor, STATES["proprio_obs"]])
      layers:
      - 256
      - 128
      - 64
      activations: elu
    output: ONE
memory:
  class: RandomMemory
  memory_size: -1
agent:
  class: PPO
  rollouts: 64
  learning_epochs: 4
  mini_batches: 32
  discount_factor: 0.99
  lambda: 0.95
  learning_rate: 0.0001
  learning_rate_scheduler: KLAdaptiveLR
  learning_rate_scheduler_kwargs:
    kl_threshold: 0.008
  state_preprocessor: null
  state_preprocessor_kwargs: null
  value_preprocessor: RunningStandardScaler
  value_preprocessor_kwargs: null
  random_timesteps: 0
  learning_starts: 0
  grad_norm_clip: 1.0
  ratio_clip: 0.2
  value_clip: 0.2
  clip_predicted_values: true
  entropy_loss_scale: 0.0
  value_loss_scale: 1.0
  kl_threshold: 0.0
  rewards_shaper_scale: 1.0
  time_limit_bootstrap: false
  experiment:
    directory: /workspace/tacex/logs/skrl/ball_rolling
    experiment_name: 2025-04-08_12-09-41_ppo_torch_base_env
    write_interval: 100
    checkpoint_interval: 10000
    wandb: false
    wandb_kwargs:
      sync_tensorboard: true
      project: ball_rolling_tactile
trainer:
  class: SequentialTrainer
  timesteps: 2400000
  environment_info: log
  close_environment_at_exit: false
