name: tacex

x-default-isaac-lab-template-environment: &default-isaac-lab-template-environment
  - OMNI_KIT_ALLOW_ROOT=1

x-default-isaac-lab-template-deploy: &default-isaac-lab-template-deploy
  resources:
    reservations:
      devices:
        - driver: nvidia
          count: all
          capabilities: [ gpu ]

services:
  isaac-lab-template:
    env_file: .env.base
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - ISAACLAB_BASE_IMAGE_ARG=${ISAACLAB_BASE_IMAGE}
        - ISAACLAB_EXTENSION_TEMPLATE_PATH_ARG=${ISAACLAB_EXTENSION_TEMPLATE_PATH}
        - ISAACLAB_PATH_ARG=${DOCKER_ISAACLAB_PATH}
    image: isaac-lab-tacex
    container_name: isaac-lab-tacex
    # This overlay allows changes on the local files to
    # be reflected within the container immediately
    # (dont bind the whole TacEx directory, otherwise we cannot create symbolic link with Dockerfile commands)
    volumes:
      - type: bind
        source: ../
        target: ${ISAACLAB_EXTENSION_TEMPLATE_PATH}
    network_mode: host
    environment: *default-isaac-lab-template-environment
    deploy: *default-isaac-lab-template-deploy
    # This is the entrypoint for the container
    entrypoint: bash
    stdin_open: true
    tty: true
