seed: 42
models:
  separate: true
  policy:
    clip_actions: false
    clip_log_std: true
    initial_log_std: 0
    min_log_std: -20.0
    max_log_std: 2.0
    input_shape: Shape.STATES
    hiddens:
    - 256
    - 128
    - 64
    hidden_activation:
    - elu
    - elu
    - elu
    output_shape: Shape.ACTIONS
    output_activation: ''
    output_scale: 1.0
  value:
    clip_actions: false
    input_shape: Shape.STATES
    hiddens:
    - 256
    - 128
    - 64
    hidden_activation:
    - elu
    - elu
    - elu
    output_shape: Shape.ONE
    output_activation: ''
    output_scale: 1.0
agent:
  rollouts: 16
  learning_epochs: 8
  mini_batches: 8
  discount_factor: 0.99
  lambda: 0.95
  learning_rate: 0.0003
  learning_rate_scheduler: KLAdaptiveLR
  learning_rate_scheduler_kwargs:
    kl_threshold: 0.008
  state_preprocessor: RunningStandardScaler
  state_preprocessor_kwargs: null
  value_preprocessor: RunningStandardScaler
  value_preprocessor_kwargs: null
  random_timesteps: 0
  learning_starts: 0
  grad_norm_clip: 1.0
  ratio_clip: 0.2
  value_clip: 0.2
  clip_predicted_values: true
  entropy_loss_scale: 0.0
  value_loss_scale: 2.0
  kl_threshold: 0
  rewards_shaper_scale: 0.01
  experiment:
    directory: /workspace/tacex/logs/skrl/ball_rolling_privileged
    experiment_name: 2025-03-07_15-22-56_ppo_torch
    write_interval: 1200
    checkpoint_interval: auto
    wandb: false
    wandb_kwargs:
      sync_tensorboard: true
      project: ball_rolling
trainer:
  timesteps: 2400000
  environment_info: log
  close_environment_at_exit: false
