from __future__ import annotations

import logging
import math
import re
from typing import TYPE_CHECKING, Literal

import torch

import carb
import omni.physics.tensors.impl.api as physx
from isaacsim.core.utils.extensions import enable_extension
from pxr import Gf, Sdf, UsdGeom, Vt

import isaaclab.sim as sim_utils
import isaaclab.utils.math as math_utils
from isaaclab.actuators import ImplicitActuator
from isaaclab.assets import Articulation, DeformableObject, RigidObject
from isaaclab.managers import EventTermCfg, ManagerTermBase, SceneEntityCfg
from isaaclab.sim.utils.stage import get_current_stage
from isaaclab.terrains import TerrainImporter
from isaaclab.utils.version import compare_versions, get_isaac_sim_version

if TYPE_CHECKING:
    from isaaclab.envs import ManagerBasedEnv

# import logger
logger = logging.getLogger(__name__)


class randomize_rigid_body_material(ManagerTermBase):
    """Randomize the physics materials on all geometries of the asset.

    This function creates a set of physics materials with random static friction, dynamic friction, and restitution
    values. The number of materials is specified by ``num_buckets``. The materials are generated by sampling
    uniform random values from the given ranges.

    The material properties are then assigned to the geometries of the asset. The assignment is done by
    creating a random integer tensor of shape  (num_instances, max_num_shapes) where ``num_instances``
    is the number of assets spawned and ``max_num_shapes`` is the maximum number of shapes in the asset (over
    all bodies). The integer values are used as indices to select the material properties from the
    material buckets.

    If the flag ``make_consistent`` is set to ``True``, the dynamic friction is set to be less than or equal to
    the static friction. This obeys the physics constraint on friction values. However, it may not always be
    essential for the application. Thus, the flag is set to ``False`` by default.

    .. attention::
        This function uses CPU tensors to assign the material properties. It is recommended to use this function
        only during the initialization of the environment. Otherwise, it may lead to a significant performance
        overhead.

    .. note::
        PhysX only allows 64000 unique physics materials in the scene. If the number of materials exceeds this
        limit, the simulation will crash. Due to this reason, we sample the materials only once during initialization.
        Afterwards, these materials are randomly assigned to the geometries of the asset.
    """


def __init__(self, cfg: EventTermCfg, env: ManagerBasedEnv):
    """Initialize the term.

    Args:
        cfg: The configuration of the event term.
        env: The environment instance.

    Raises:
        ValueError: If the asset is not a RigidObject or an Articulation.
    """
    super().__init__(cfg, env)

    # extract the used quantities (to enable type-hinting)
    self.asset_cfg: SceneEntityCfg = cfg.params["asset_cfg"]
    self.asset: RigidObject | Articulation = env.scene[self.asset_cfg.name]

    if not isinstance(self.asset, (RigidObject, Articulation)):
        raise ValueError(
            f"Randomization term 'randomize_rigid_body_material' not supported for asset: '{self.asset_cfg.name}'"
            f" with type: '{type(self.asset)}'."
        )

    # obtain number of shapes per body (needed for indexing the material properties correctly)
    # note: this is a workaround since the Articulation does not provide a direct way to obtain the number of shapes
    #  per body. We use the physics simulation view to obtain the number of shapes per body.
    if isinstance(self.asset, Articulation) and self.asset_cfg.body_ids != slice(None):
        self.num_shapes_per_body = []
        for link_path in self.asset.root_physx_view.link_paths[0]:
            link_physx_view = self.asset._physics_sim_view.create_rigid_body_view(link_path)  # type: ignore
            self.num_shapes_per_body.append(link_physx_view.max_shapes)
        # ensure the parsing is correct
        num_shapes = sum(self.num_shapes_per_body)
        expected_shapes = self.asset.root_physx_view.max_shapes
        if num_shapes != expected_shapes:
            raise ValueError(
                "Randomization term 'randomize_rigid_body_material' failed to parse the number of shapes per body."
                f" Expected total shapes: {expected_shapes}, but got: {num_shapes}."
            )
    else:
        # in this case, we don't need to do special indexing
        self.num_shapes_per_body = None

    # obtain parameters for sampling friction and restitution values
    static_friction_range = cfg.params.get("static_friction_range", (1.0, 1.0))
    dynamic_friction_range = cfg.params.get("dynamic_friction_range", (1.0, 1.0))
    restitution_range = cfg.params.get("restitution_range", (0.0, 0.0))
    num_buckets = int(cfg.params.get("num_buckets", 1))

    # sample material properties from the given ranges
    # note: we only sample the materials once during initialization
    #   afterwards these are randomly assigned to the geometries of the asset
    range_list = [static_friction_range, dynamic_friction_range, restitution_range]
    ranges = torch.tensor(range_list, device="cpu")
    self.material_buckets = math_utils.sample_uniform(
        ranges[:, 0], ranges[:, 1], (num_buckets, 3), device="cpu"
    )

    # ensure dynamic friction is always less than static friction
    make_consistent = cfg.params.get("make_consistent", False)
    if make_consistent:
        self.material_buckets[:, 1] = torch.min(
            self.material_buckets[:, 0], self.material_buckets[:, 1]
        )


def __call__(
    self,
    env: ManagerBasedEnv,
    env_ids: torch.Tensor | None,
    static_friction_range: tuple[float, float],
    dynamic_friction_range: tuple[float, float],
    restitution_range: tuple[float, float],
    num_buckets: int,
    asset_cfg: SceneEntityCfg,
    make_consistent: bool = False,ppppppppppppppppppppppppppppppppppppppppppppppppppppp
):
    # resolve environment ids
    if env_ids is None:
        env_ids = torch.arange(env.scene.num_envs, device="cpu")
    else:
        env_ids = env_ids.cpu()

    # randomly assign material IDs to the geometries
    total_num_shapes = self.asset.root_physx_view.max_shapes
    bucket_ids = torch.randint(
        0, num_buckets, (len(env_ids), total_num_shapes), device="cpu"
    )
    material_samples = self.material_buckets[bucket_ids]

    # retrieve material buffer from the physics simulation
    materials = self.asset.root_physx_view.get_material_properties()

    # update material buffer with new samples
    if self.num_shapes_per_body is not None:
        # sample material properties from the given ranges
        for body_id in self.asset_cfg.body_ids:
            # obtain indices of shapes for the body
            start_idx = sum(self.num_shapes_per_body[:body_id])
            end_idx = start_idx + self.num_shapes_per_body[body_id]
            # assign the new materials
            # material samples are of shape: num_env_ids x total_num_shapes x 3
            materials[env_ids, start_idx:end_idx] = material_samples[
                :, start_idx:end_idx
            ]
    else:
        # assign all the materials
        materials[env_ids] = material_samples[:]

    # apply to simulation
    self.asset.root_physx_view.set_material_properties(materials, env_ids)
